=== duang256/IdeaResp/xml/src/xml/scores.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT scores (student+)>
        <!--同级应该用逗号隔开-->
        <!ELEMENT student (name,lessons,score)>
        <!--#PCDATA代表限定字符-->
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT lessons (#PCDATA)>
        <!ELEMENT score (#PCDATA)>
        <!--ATTLIST可以声明参数-->
        <!ATTLIST student id CDATA #REQUIRED>

=== duang256/IdeaResp/xml/out/production/xml/xml/scores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE scores SYSTEM "scores.dtd">

<scores>
    <student id="001">
        <name>网通</name>
        <lessons>java</lessons>
        <score>89</score>
    </student>
    <student id="002">
        <name>校长</name>
        <lessons>高数</lessons>
        <score>99</score>
    </student>
</scores>
